


<div class="footer-col-links" style="grid-area: links; display: flex; flex-wrap: wrap; margin: 20px 0 20px 0;">
	<div class="footer-div-content">
		<a href="content/brands">Brands</a><br>
		<a href="content/careers">Careers</a><br>
		<a href="content/contactus">Contact Us</a><br>
		<a href="content/about-us">About</a><br>
	</div>
	<div class="footer-div-content">
		<a href="page/myorders">My Orders</a><br>
		<a href="page/myvouchers">My Coupon / Vouchers</a><br>
		<a href="content/stores">Stores</a><br>
		<a href="content/faq">FAQ</a><br>
		<a href="content/termsofuse">Terms of Use</a><br>
		<a href="content/privacypolicy">Privacy Policy</a><br>
	</div>
</div>


<div class="footer-col-partner hidden" style="grid-area: partner; display: flex; justify-content: center; flex-wrap: wrap; margin: 20px 0 20px 0;">
	<div class="footer-div-content">
		<!-- LOGO-LOGO PARTNER disini -->
	</div>
</div>


<div class="footer-col-company" style="grid-area: company; display: flex; flex-direction: column; justify-content: center; margin: 20px 0 20px 0;">
	<div class="footer-div-content" style="font-size: 0.9em; line-height: 20px;">
		<b>PT. TRANS FASHION INDONESIA</b><br>
		Menara Mega Syariah 18th Floor<br>
		Jl. H.R. Rasuna Said Kav 19A<br>
		Jakarta Selatan 12950<br>
		Ph: +62 21 2985 2112<br>
		WA: +62 811 1902 6480<br>
	</div>
	<div class="footer-div-content">
		<a href="https://www.instagram.com/transfashionindonesia" class="footer-logolink logo-instagram">https://www.instagram.com/transfashionindonesia</a>
		<a href="https://www.facebook.com/transfashionindonesia.ctcorp" class="footer-logolink logo-facebook">https://www.facebook.com/transfashionindonesia.ctcorp</a>
		<a href="https://www.youtube.com/channel/UCC88smmXqjhNQkTBNkG2mHg/playlists" class="footer-logolink logo-youtube">https://www.youtube.com/channel/UCC88smmXqjhNQkTBNkG2mHg/playlists</a>
		<a href="https://www.tiktok.com/@transfashionindonesia" class="footer-logolink logo-tiktok">https://www.tiktok.com/@transfashionindonesia</a>
		<a href="https://www.linkedin.com/company/trans-fashion-indonesia" class="footer-logolink logo-linkedin">https://www.linkedin.com/company/trans-fashion-indonesia</a>
	</div class="footer-div-content">
	<div class="footer-div-content" data-display="mobile">
		<a href="https://www.transfashionindonesia.com" class="logo-transfashion">https://www.transfashionindonesia.com</a>
		<a href="https://www.ctcorpora.com" class="logo-ctcorp">https://www.ctcorpora.com</a>
	</div>
</div>

<div style="grid-area: corporatelogo; display: flex; margin: 20px 0 30px 0; column-gap: 20px" data-display="desktop">
	<a href="https://www.transfashionindonesia.com" class="logo-transfashion">https://www.transfashionindonesia.com</a>
	<a href="https://www.ctcorpora.com" class="logo-ctcorp">https://www.ctcorpora.com</a>
</div>
