<div class="dropdown">
	<a class="dropbtn menubar-item">Women</a>
	<div class="dropdown-content">
		<div class="dropdown-content-container">
			<div class="dropdown-content-column">
				<div><a href="catalog/eag/women/accessories">Accessories</a></div>
				<div><a href="catalog/eag/women/bags">Bags</a></div>
				<div><a href="catalog/eag/women/belts">Belts</a></div>
				<div><a href="/catalog/eag/women/readytowear">Ready to Wear</a></div>
			</div>
			<div class="dropdown-content-column">
				<div><a href="catalog/eag/women/shoes">Shoes</a></div>
				<div><a href="catalog/eag/women/slg">Small Leather Goods</a></div>
				<div><a href="catalog/eag/women/watches">Watches</a></div>
			</div>
			<div class="dropdown-content-column"></div>
		</div>
	</div>
</div>
<div class="dropdown">
	<a class="dropbtn menubar-item">Men</a>
	<div class="dropdown-content">
		<div class="dropdown-content-container">
			<div class="dropdown-content-column">
				<div><a href="catalog/eag/men/bags">Bags</a></div>
				<div><a href="catalog/eag/men/belts">Belts</a></div>
			</div>
			<div class="dropdown-content-column">
				<div><a href="catalog/eag/men/shoes">Shoes</a></div>
				<div><a href="catalog/eag/men/slg">Small Leather Goods</a></div>
				<div><a href="catalog/eag/men/watch">Watches</a></div>
			</div>
			<div class="dropdown-content-column"></div>
		</div>	
	</div>
</div>		
<div class="dropdown">
	<a class="dropbtn menubar-item">Brands</a>
	<div class="dropdown-content">
		<div class="dropdown-content-container">
			<div class="dropdown-content-column">
				<div><a href="content/video">Aigner</a></div>
				<div><a href="content/video">Canali</a></div>
				<div><a href="content/video">Find Kapoor</a></div>
			</div>
			<div class="dropdown-content-column">
				<div><a href="content/collectionbook">Furla</a></div>
				<div><a href="content/collectionbook">Geox</a></div>
				<div><a href="content/collectionbook">Moschino</a></div>
			</div>
			<div class="dropdown-content-column">
				<div><a href="content/highligt">Pinko</a></div>
				<div><a href="content/highligt">Stella McCartner</a></div>
			</div>
		</div>	
	</div>
</div>

<a class="navbarlink menubar-item" href="collection/bestseller">New Collections</a>
<a class="navbarlink menubar-item" href="collection/sale" style="background-color: #800000; color: white; padding: 0 20px 0 20px;">SALE</a>