<div class="dropdown">
	<a class="dropbtn menubar-item">Women</a>
	<div class="dropdown-content">
		<div class="dropdown-content-container">
			<div class="dropdown-content-column">
				<div><a href="page/list/all/women/accessories">Accessories</a></div>
				<div><a href="page/list/all/women/bags">Bags</a></div>
				<div><a href="page/list/all/women/belts">Belts</a></div>
				<div><a href="page/list/all/women/readytowear">Ready to Wear</a></div>
			</div>
			<div class="dropdown-content-column">
				<div><a href="page/list/all/women/shoes">Shoes</a></div>
				<div><a href="page/list/all/women/slg">Small Leather Goods</a></div>
				<div><a href="page/list/all/women/watches">Watches</a></div>
			</div>
			<div class="dropdown-content-column"></div>
		</div>
	</div>
</div>
<div class="dropdown">
	<a class="dropbtn menubar-item">Men</a>
	<div class="dropdown-content">
		<div class="dropdown-content-container">
			<div class="dropdown-content-column">
				<div><a href="page/list/all/men/bags">Bags</a></div>
				<div><a href="page/list/all/men/belts">Belts</a></div>
			</div>
			<div class="dropdown-content-column">
				<div><a href="page/list/all/men/shoes">Shoes</a></div>
				<div><a href="page/list/all/men/slg">Small Leather Goods</a></div>
				<div><a href="page/list/all/men/watch">Watches</a></div>
			</div>
			<div class="dropdown-content-column"></div>
		</div>	
	</div>
</div>		
<div class="dropdown">
	<a class="dropbtn menubar-item">Brands</a>
	<div class="dropdown-content">
		<div class="dropdown-content-container">
			<div class="dropdown-content-column">
				<div><a href="content/brands/aigner">Aigner</a></div>
				<div><a href="content/brands/canali">Canali</a></div>
				<div><a href="content/brands/find-kapoor">Find Kapoor</a></div>
			</div>
			<div class="dropdown-content-column">
				<div><a href="content/brands/furla">Furla</a></div>
				<div><a href="content/brands/geox">Geox</a></div>
				<div><a href="content/brands/moschino">Moschino</a></div>
			</div>
			<div class="dropdown-content-column">
				<div><a href="content/brands/pinko">Pinko</a></div>
				<div><a href="content/brands/stella-mccartney">Stella McCartney</a></div>
			</div>
		</div>	
	</div>
</div>

<a class="navbarlink menubar-item" href="page/newcollections">New Collections</a>
<a class="navbarlink menubar-item" href="page/sale" style="background-color: #800000; color: white; padding: 0 20px 0 20px;">SALE</a>