<?php 
// get required page object
use AgungDhewe\Webservice\Page;
$page = Page::getWebPageObject($this);
$tpl = $page->getTemplate();
?> 

{block name="title"}About Us{/block}
{block name="header-style"}
<link rel="stylesheet" href="<?=$page->getPageAssetUrl('content.css')?>">
{/block}

<article>
<div class="judul-artikel">
   <h1> Our Story </h1>
   <p>#LiveYourLifeStyle</p>
   
</div>
<p>
    fahgsfkashfasgadkjhaskjfasjfbaskjbfashcbhb
    aeyvbcasbcashbcashbcashcbsa
    kcbaskcbashkcsakhssbckbaskcbsajchvsjhcvuyv
    fawhvfhvscjvascjhvaschjavscvhcjvcsajhcvajsscascasgag
</p>
</article>