<?php 
// get required page object
use AgungDhewe\Webservice\Page;
$page = Page::getWebPageObject($this);
$tpl = $page->getTemplate();
?> 
{block name="title"}Home{/block}


If you love indulging in fashion therapy while strolling through the mall, you won't want to miss the chance to visit AIGNER Plaza Indonesia. Enjoy a wide array of irresistible promotions, which are a real bargain after you receive your payday check, don’t you think? There was also an exciting activity held on Saturday, August 26th, where you could get free ice cream at the AIGNER Plaza Indonesia store – how cool is that? All participants had to do was scan their WhatsApp barcode or take a photo at the store and upload it to Instagram – it’s as easy as ABCD. Not only did everyone have a fantastic time, but local fashion influencer Alessandro Georgie (Instagram profile: @alegeor) also joined in and showcased his favorite AIGNER bag, the most-coveted Delia bag. Shall we take a sneak peek?


<?php 
for ($i=0; $i<100; $i++) {
	echo $i . "<br>";	
}
?>








