<?php 
	use AgungDhewe\Webservice\WebTemplate;
	$tpl = WebTemplate::getTemplateObject($this);
?><!DOCTYPE html>
<html>
	<head>
		<title><?=$tpl->getTitle()?></title>
		<link rel="icon" href="/favicon.ico">
		<link rel="stylesheet" href="<?=$tpl->getTemplateAssetUrl('assets/style.css')?>">
		<?=$tpl->getBlockContent('header-metadata')?> 
		<?=$tpl->getBlockContent('header-style')?> 
		<script>
			var $ui = {};
		</script>
		<?=$tpl->getBlockContent('header-script')?> 
	</head>

	<body>
		<div class="logo">
			<a href="<?=$tpl->getUrl('')?>"> 
			<img src="<?=$tpl->getTemplateAssetUrl('assets/logo.png')?>" alt="">
			</a>
		</div>
		<header>
			<h1>MyWeb Template</h1>
		</header>
		<nav></nav>
		<main>
			<?=$tpl->getMainContent()?> 
		</main>
		<footer>
			<p>Copyright &copy; <?=date('Y')?>. All rights reserved.</p>
		</footer>
	</body>	
	<?=$tpl->getBlockContent('footer-script')?> 
</body>