<?php 
	define('__TEMPLATE_NAME__', 'transfashionid');
	define('__SEARCH_PLACEHOLDER__', 'Search for product');


	use Transfashion\Transfashionid\Template;
	$tpl = Template::getTemplate($this);
?><!DOCTYPE html>
<html>
	<head>
		<title><?=$tpl->getTitle()?></title>
		<base href="<?=$tpl->getBaseHref()?>">
		<meta name="viewport" content="width=device-width, user-scalable=no, initial-scale=1.0, maximum-scale=1.0, minimum-scale=1.0">
		<meta http-equiv="X-UA-Compatible" content="IE=edge">
		<link rel="icon" href="favicon.ico">
		<link rel="manifest" href="manifest.json">
		
		<style>

		</style>
		<link rel="stylesheet" href="<?=$tpl->getTemplateAssetUrl(__TEMPLATE_NAME__.'.css')?>">
		<link rel="stylesheet" href="<?=$tpl->getTemplateAssetUrl('assets/dw-promoter.css')?>">
		<link rel="stylesheet" href="<?=$tpl->getTemplateAssetUrl('assets/dw-style.css')?>">
		<link rel="stylesheet" href="<?=$tpl->getTemplateAssetUrl('assets/dw-searchbox.css')?>">
		<link rel="stylesheet" href="<?=$tpl->getTemplateAssetUrl('assets/dw-dropdownmenu.css')?>">
		<link rel="stylesheet" href="<?=$tpl->getTemplateAssetUrl('assets/dw-pagemask.css')?>">
		<link rel="stylesheet" href="<?=$tpl->getTemplateAssetUrl('assets/sosmed-icons/icons.css')?>">

		<link rel="preload" href="<?=$tpl->getTemplateAssetUrl('transfashionid-logo-icon-40x40.svg')?>" as="image" type="image/svg+xml">
		<link rel="preload" href="<?=$tpl->getTemplateAssetUrl('transfashionid-logo-text-135x40.svg')?>" as="image" type="image/svg+xml">


		<?=$tpl->getBlockContent('header-metadata')?> 
		<?=$tpl->getBlockContent('header-style')?> 
		<script>
			var $uilayout = {};
		</script>
		<?=$tpl->getBlockContent('header-script')?> 
	</head>

	<body>
		<!-- 
		CATATAN DESIGNER:	
		* tata letak tag, main, footer, header, dan lain lain JANGAN DIUBAH URUTANNYA
		* karena diatur sesuai layer, sehingga tidak perlu menggunakan z-index
		* urutan tata letak tidak berpengaruh pada posisi di layar, karena menggunakan GRID LAYOUT
		-->
		
		<main id="main">
			<?=$tpl->getMainContent()?> 
		</main>

		<footer>
			<nav>
				<?php $tpl->includeFooterNavContent() ?>
			</nav>
		</footer>
		<div class="footer-copyrightbar">&copy;<?=date('Y')?>. PT. Trans Fashion Indonesia. All rights reserved.</div>

		
		<!-- MASKING MAIN DIV: BEGIN -->
		<div id="main-mask" class="hidden">
		</div>
		<!-- MASKING MAIN DIV: END -->

		<header id="head">
			
			<!-- PROMOTER:BEGIN -->
			 <?php if ($promotertext=$tpl->getPromoterText()) { ?>
			<div class="dw-promoter" style="grid-area: promoter">
				<span style="grid-area: running-text">
					<span><?=$promotertext?></span>
				</span>
				<button style="grid-area: button"></button>
			</div>
			<?php } ?>
			<!-- PROMOTER:END -->
	

			<!-- HEADER LEFT:BEGIN -->
			<div class="head-mainrow head-left" style="grid-area: head-left" data-display="mobile">
				<button id="btn_sidebar_show" class="dw-iconbutton" data-icon="menu"></button>
			</div>
			<div class="head-mainrow head-left" style="grid-area: head-left" data-display="desktop">
				<div class="dw-searchbox" style="width: 200px">
					<input id="input_desktop_search" type="text" placeholder="<?=__SEARCH_PLACEHOLDER__?>" closeonblur="true">
					<button></button>
				</div>
			</div>
			<!-- HEADER LEFT:END -->


			<!-- HEADER RIGHT:BEGIN -->
			<div class="head-mainrow head-right" style="grid-area: head-right;" data-display="mobile">
				<button class="dw-iconbutton headLoginRegister" data-icon="account" onclick="window.location='/page/login'"></button>
				<button class="dw-iconbutton" data-icon="chart"></button>
				<button id="btn_search_togle" class="dw-iconbutton" data-icon="search"></button>
			</div>
			<div class="head-mainrow head-right" style="grid-area: head-right;" data-display="desktop">
				<button class="dw-iconbutton headLoginRegister" data-icon="account" onclick="window.location='/page/login'">Login / Register</button>
				<button class="dw-iconbutton" data-icon="chart">Cart</button>
			</div>
			<!-- HEADER RIGHT:END -->	



			<!-- HEADER MIDDLE:BEGIN -->
			<div class="head-mainrow head-middle" style="grid-area: head-middle">
				<!-- LOGO: BEGIN -->
				<a href="/">
					<div class="logo">
					</div>
				</a>
				<!-- LOGO: END -->

				<!-- SEARCH DIALOG: BEGIN -->
				<div id="searchdialog" class="hidden">
					<div class="head-searchbar" data-display="mobile">
						<div class="dw-searchbox" style="width: 100%">
							<input id="input_mobile_search" type="text" placeholder="<?=__SEARCH_PLACEHOLDER__?>">
							<button functional="close"></button>
						</div>
					</div>
					<div class="head-searchresult">
						<div id="searchdialog-result" class="hidden">
							search result
						</div>
						<div id="searchdialog-popular" class="hidden">
							<div>Try popular search terms:</div>
							<a>bags</a><br>
							<a>shoes</a><br>
							<a>accessories</a><br>
						</div>

					</div>
				</div>
				<!-- SEARCH DIALOG: END -->
			</div>
			<!-- HEADER MIDDLE:END -->

			<nav id="mainmenu-desktop" style="grid-area: menubar; opacity: 0" data-display="desktop">
				<?php $tpl->includeMenubarNavContent() ?>
			</nav>
		</header>	

		<nav id="sidebar" class="sidebar-hidden" data-display="mobile">
			<div class="sidebar-header">
				<div class="sidebar-header" style="grid-area: head-left;"></div>
				<div class="sidebar-header logo" style="grid-area: head-middle;"></div>
				<div class="sidebar-header" style="grid-area: head-right; display: flex; justify-content: flex-end; margin-right: 10px; margin-top: 3px;">
					<button  id="btn_sidebar_hide" class="dw-iconbutton" data-icon="close"></button>
				</div>
			</div>
			<div class="sidebar-nav">
				<?php $tpl->includeSidebarNavContent() ?>
			</div>
		</nav>


		<!--	
		<div class="dw-pagemask">
			<div style="grid-area: messagebox">
				ini test message
			</div>	
		</div>
		-->

	</body>	
	<?=$tpl->getBlockContent('footer-script')?>
	<script>
		window.addEventListener("load", async (event) => {
			await window.$uilayout.Init();
			var main = document.querySelector('main');
			var menu = document.getElementById('mainmenu-desktop');
			main.style.opacity = 1;
			menu.style.opacity = 1;
		})
	</script>
	<script type="module">
		import * as uilayout from './template/<?=__TEMPLATE_NAME__?>.mjs'
		window.$uilayout = uilayout
	</script>
</body>