<?php 
	use AgungDhewe\Webservice\WebTemplate;
	$tpl = WebTemplate::getTemplateObject($this);
?><!DOCTYPE html>
<html>
	<head>
		<title><?=$tpl->getTitle()?></title>
		<base href="<?=$tpl->getBaseHref()?>">
		<meta name="viewport" content="width=device-width, user-scalable=no, initial-scale=1.0, maximum-scale=1.0, minimum-scale=1.0">
		<meta http-equiv="X-UA-Compatible" content="IE=edge">
		<link rel="icon" href="favicon.ico">
		<link rel="manifest" href="manifest.json">
		
		
		<style>
			:root {
				--promoter-h-desktop: 23px;
				--promoter-h-mobile: 23px;

				--header-h-desktop: 80px;
				--header-h-mobile: 50px;

				--logo-w-desktop: 135px;
				--logo-h-desktop: 40px;

				--logo-w-mobile: 30px;
				--logo-h-mobile: 30px;
			}
		</style>
		<link rel="stylesheet" href="<?=$tpl->getTemplateAssetUrl('assets/layout.css')?>">
		<link rel="stylesheet" href="<?=$tpl->getTemplateAssetUrl('assets/dw-style.css')?>">
		<link rel="stylesheet" href="<?=$tpl->getTemplateAssetUrl('assets/dw-searchbox.css')?>">
		<link rel="stylesheet" href="<?=$tpl->getTemplateAssetUrl('assets/dw-promoter.css')?>">



		<?=$tpl->getBlockContent('header-metadata')?> 
		<?=$tpl->getBlockContent('header-style')?> 
		<script>
			var $uilayout = {};
		</script>
		<?=$tpl->getBlockContent('header-script')?> 
	</head>

	<body>
		
		<main>
			<?=$tpl->getMainContent()?> 
		</main>
		<footer>
			<p>Copyright &copy; <?=date('Y')?>. All rights reserved.</p>
		</footer>




		<!-- DESKTOP:BEGIN -->
		<header id="header-desktop" data-display="desktop">
			<div class="head-mainrow head-left"><?php require_once join(DIRECTORY_SEPARATOR, [__DIR__, 'headleft-desktop.phtml'])?></div>
			<div class="head-mainrow head-middle">
				<img alt="TransFashion" class="logo-image" src="<?=$tpl->getTemplateAssetUrl('transfashionid-logo-text-135x40.svg')?>">
			</div>
			<div class="head-mainrow head-right"><?php require_once join(DIRECTORY_SEPARATOR, [__DIR__, 'headright-desktop.phtml'])?></div>
			<nav data-display="desktop"><?php require_once join(DIRECTORY_SEPARATOR, [__DIR__, 'nav-desktop.phtml'])?></nav>
		</header>
		<!-- DESKTOP:END -->

		<!-- MOBILE:BEGIN -->
		<header id="header-mobile" data-display="mobile">
			<div class="head-mainrow head-left"><?php require_once join(DIRECTORY_SEPARATOR, [__DIR__, 'headleft-mobile.phtml'])?></div>
			<div class="head-mainrow head-middle">
				<img alt="TransFashion" class="logo-image" src="<?=$tpl->getTemplateAssetUrl('transfashionid-logo-icon-40x40.svg')?>">
			</div>
			<div class="head-mainrow head-right"><?php require_once join(DIRECTORY_SEPARATOR, [__DIR__, 'headright-mobile.phtml'])?></div>
		</header>
		<!-- MOBILE:END -->


		

		<nav data-display="mobile" class="hidden"><?php require_once join(DIRECTORY_SEPARATOR, [__DIR__, 'nav-mobile.phtml'])?></nav>


	</body>	
	<?=$tpl->getBlockContent('footer-script')?>
	<script>
		window.addEventListener("load", async (event) => {
			await window.$uilayout.Init()
		})
	</script>
	<script type="module">
		import * as uilayout from './template/assets/layout.mjs'
		window.$uilayout = uilayout
	</script>
</body>